<?php

namespace App\Helpers;

use App\Models\Absensi;
use App\Models\Kelas;
use Illuminate\Http\Request;

class ExportHelper
{
    /**
     * Build query dengan filter
     */
    public static function buildAbsensiQuery(Request $request)
    {
        $query = Absensi::with(['siswa', 'kelas']);

        if ($request->filled('kelas_id')) {
            $query = $query->where('kelas_id', $request->kelas_id);
        }

        if ($request->filled('tanggal_mulai') && $request->filled('tanggal_akhir')) {
            $query = $query->whereBetween('tanggal_absen', [
                $request->tanggal_mulai,
                $request->tanggal_akhir
            ]);
        }

        if ($request->filled('status')) {
            $query = $query->where('status', $request->status);
        }

        return $query->orderBy('tanggal_absen', 'desc');
    }

    /**
     * Generate HTML table untuk PDF
     */
    public static function generateHtmlTable($absensi, $kelas = null, $tanggalMulai = null, $tanggalAkhir = null)
    {
        $html = '<html><head><meta charset="utf-8"><style>';
        $html .= 'body { font-family: Arial, sans-serif; margin: 20px; }';
        $html .= 'h2 { text-align: center; color: #333; margin-bottom: 20px; }';
        $html .= 'p { margin: 5px 0; font-size: 14px; }';
        $html .= 'table { width: 100%; border-collapse: collapse; margin-top: 20px; }';
        $html .= 'th { background-color: #667eea; color: white; padding: 12px; text-align: left; font-weight: bold; border: 1px solid #ddd; }';
        $html .= 'td { padding: 10px; border: 1px solid #ddd; font-size: 13px; }';
        $html .= 'tr:nth-child(even) { background-color: #f9f9f9; }';
        $html .= 'tr:hover { background-color: #f0f0f0; }';
        $html .= '.status-hadir { color: #28a745; font-weight: bold; }';
        $html .= '.status-sakit { color: #ffc107; font-weight: bold; }';
        $html .= '.status-izin { color: #17a2b8; font-weight: bold; }';
        $html .= '.status-alpa { color: #dc3545; font-weight: bold; }';
        $html .= 'footer { text-align: center; margin-top: 30px; font-size: 12px; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }';
        $html .= '</style></head><body>';

        $html .= '<h2>📋 Laporan Data Absensi Siswa</h2>';
        $html .= '<p><strong>Tanggal Cetak:</strong> ' . now()->format('d F Y H:i:s') . '</p>';
        
        if ($kelas) {
            $html .= '<p><strong>Kelas:</strong> ' . htmlspecialchars($kelas->nama_kelas) . '</p>';
        }
        
        if ($tanggalMulai && $tanggalAkhir) {
            $html .= '<p><strong>Periode:</strong> ' . $tanggalMulai . ' hingga ' . $tanggalAkhir . '</p>';
        }
        
        $html .= '<p><strong>Total Data:</strong> ' . count($absensi) . ' records</p>';

        $html .= '<table>';
        $html .= '<tr>';
        $html .= '<th style="width: 5%;">No</th>';
        $html .= '<th style="width: 25%;">Nama Siswa</th>';
        $html .= '<th style="width: 15%;">Kelas</th>';
        $html .= '<th style="width: 15%;">Tanggal</th>';
        $html .= '<th style="width: 12%;">Status</th>';
        $html .= '<th style="width: 28%;">Keterangan</th>';
        $html .= '</tr>';

        $statusClass = [
            'Hadir' => 'status-hadir',
            'Sakit' => 'status-sakit',
            'Izin' => 'status-izin',
            'Alpa' => 'status-alpa'
        ];

        foreach ($absensi as $key => $item) {
            $status = $item->status ?? 'Tidak Ada';
            $statusCls = $statusClass[$status] ?? '';
            
            $html .= '<tr>';
            $html .= '<td>' . ($key + 1) . '</td>';
            $html .= '<td>' . htmlspecialchars($item->siswa->nama_lengkap ?? '-') . '</td>';
            $html .= '<td>' . htmlspecialchars($item->kelas->nama_kelas ?? '-') . '</td>';
            $html .= '<td>' . ($item->tanggal_absen ? $item->tanggal_absen->format('d-m-Y') : '-') . '</td>';
            $html .= '<td class="' . $statusCls . '">' . htmlspecialchars($status) . '</td>';
            $html .= '<td>' . htmlspecialchars($item->keterangan ?? '-') . '</td>';
            $html .= '</tr>';
        }

        $html .= '</table>';
        $html .= '<footer>Generated by AbsenKelas | Sistem Manajemen Absensi Siswa</footer>';
        $html .= '</body></html>';

        return $html;
    }

    /**
     * Generate Excel data array
     */
    public static function generateExcelData($absensi)
    {
        $data = [];
        $data[] = ['No', 'Nama Siswa', 'Kelas', 'Tanggal', 'Status', 'Keterangan'];

        foreach ($absensi as $key => $item) {
            $data[] = [
                $key + 1,
                $item->siswa->nama_lengkap ?? '-',
                $item->kelas->nama_kelas ?? '-',
                $item->tanggal_absen ? $item->tanggal_absen->format('d-m-Y') : '-',
                $item->status ?? '-',
                $item->keterangan ?? '-'
            ];
        }

        return $data;
    }

    /**
     * Safe file path creation
     */
    public static function getTempFilePath($filename)
    {
        @mkdir(storage_path('app/temp'), 0777, true);
        return storage_path('app/temp/' . $filename);
    }

    /**
     * Generate unique filename
     */
    public static function generateFilename($prefix = 'export')
    {
        return $prefix . '_' . date('Y-m-d_H-i-s') . '.tmp';
    }
}
